SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- Data de Usuario
INSERT INTO `usuario` (`id`, `nombre_apellido`, `nombre_usu`, `pass`, `rol_id`) VALUES(3, 'Carlos Monti', 'cmonti', 'cmonti201210', 1);
INSERT INTO `usuario` (`id`, `nombre_apellido`, `nombre_usu`, `pass`, `rol_id`) VALUES(4, 'Anibal Pachano', 'apachano', 'apachano201210', 1);
INSERT INTO `usuario` (`id`, `nombre_apellido`, `nombre_usu`, `pass`, `rol_id`) VALUES(5, 'Luis Ventura', 'lventura', 'intrusos201210', 2);
INSERT INTO `usuario` (`id`, `nombre_apellido`, `nombre_usu`, `pass`, `rol_id`) VALUES(6, 'Jorge Lanata', 'jlanata', 'ppt201210', 2);


-- Data de Nota
INSERT INTO `nota` (`id`, `titulo`, `fecha_hora`, `texto`, `usuario_id`, `usuario_creador_id`) VALUES(1, 'Cromañón: el fiscal pidió la detención de todos los condenados', '2012-10-20 00:04:32', 'El fiscal ante la Cámara Federal de Casación Penal, Raúl Plee, reclamó hoy la "inmediata detención" de todos los condenados por el incendio en el boliche Cromañon por entender que hay mayores riesgos de fuga ante la certera posibilidad que enfrenta la mayoría de ellos de ir a prisión.\r\n\r\n\r\n"A esta altura del proceso, existe una nueva circunstancia que constituye un peligro procesal que debe ser considerado para asegurar el cumplimiento de la sentencia, y es ni más ni menos que la existencia de una condena grave de efectivo cumplimiento dictada por la sala III" de ese tribunal, argumentó Plee ante los camaristas Liliana Catucci, Mariano Borinsky y Eduardo Riggi.\r\n\r\n\r\nY por ello solicitó la "inmediata detención" del ex gerenciador de Cromañón, Omar Chabán, del ex subcomisario Carlos Díaz, de los ex integrantes de Callejeros Patricio Santos Fontanet, Eduardo Vásquez, Christian Torrejón, Juan Carbone, Maximiliano Djerfy, Elio Delgado, Daniel Cardell, y de su ex manager, Diego Argañaraz.', 1, 1);
INSERT INTO `nota` (`id`, `titulo`, `fecha_hora`, `texto`, `usuario_id`, `usuario_creador_id`) VALUES(2, 'Microsoft presenta Windows 8, su apuesta más radical en mucho tiempo', '2012-10-20 00:04:33', 'Ya está disponible la versión de prueba y día a día se crean nuevas aplicaciones, que ya suman miles. Mientras tanto, Microsoft se prepara para presentar oficialmente la semana que viene la versión final del sistema operativo Windows 8, su apuesta más radical en mucho tiempo.\r\n\r\n\r\n\r\nSin dudas, el Windows 8 es visualmente el cambio más grande en el sistema operativo de Microsoft desde el pasaje del 3.11 al 95. Pero no es lo único ni lo más importante: se modifican, sobre todo, el modo de usarlo –es ideal para pantallas personales y táctiles y las distintas aplicaciones están muy integradas entre sí- y, aunque no lo promocionen, el propio modelo de negocios de la compañía de Bill Gates.\r\n\r\n\r\n\r\nEn el nuevo sistema, una pantalla de inicio reemplaza al tradicional escritorio, que sigue funcionando para las aplicaciones y programas que no son "nativos" de Windows 8 y, a su vez, como aplicación.\r\n\r\n\r\n\r\nEsa pantalla está organizada por módulos de distinto tamaño que pueden agruparse según los intereses del usuario; cada módulo puede ser de acceso a una aplicación o a un conjunto de aplicaciones. El recorrido es horizontal.', 5, 5);
INSERT INTO `nota` (`id`, `titulo`, `fecha_hora`, `texto`, `usuario_id`, `usuario_creador_id`) VALUES(3, 'Es todo tuyo, papá', '2012-10-21 10:48:32', 'Messi la rompió ante el Depor, hizo un hat-trick y se llevó otra pelota para su hijo Thiago, que está por nacer. En un partido chivísimo en el Riazor, y con uno menos por la expulsión de Mascherano, Barcelona ganó 5-4.
Thiago está por llegar. Y Lionel Messi tiene otra pelota para él. Porque otra vez metió un hat-trick. Y, esta vez, no sólo para lucirse: para ganar un partido chivísimo ante el Deportivo La Coruña en el Riazor. Metió goles claves: el 3-0, el 4-2 y el 5-3 (que segundos después se convirtió en el 5-4 final). Con esta victoria, el Barcelona respira y espera, a tres puntos de distancia, que el Atlético de Madrid no sume este domingo ante la Real Sociedad.
Arrancó para goleada histórica: con un 3-0 en apenas 17 minutos. Alba y Tello abrieron el marcador y fue Messi el que parecía encaminarlo, tras una jugada que arrancó Mascherano y que Fábregas decoró con un pase magistral. El descuento de Pizzi, de penal, ni siquiera despeinó al Barsa. Tampoco el 3-2, tras un error de Víctor Valdés, que dejó escapar el balón de sus manos para el gol Bergantiños. Porque Messi apareció en el final del primer tiempo para el 4-2. ¿Partido liquidado? Para nada: en el primer minuto del complemento, Pizzi, esta vez de tiro libre puso el 4-3. Y tras otro golazo de la Pulga para el 5-3 y el descuento en contra de Alba, el equipo culé sufrió como si fuera un parto, pero terminó feliz. Y Messi se llevó otra pelota, para viajar rápido de regreso a Barcelona y esperar la llegada de Thiago, que viene con más goles bajo el brazo…', 3, 6);
INSERT INTO `nota` (`id`, `titulo`, `fecha_hora`, `texto`, `usuario_id`, `usuario_creador_id`) VALUES(4, 'La NASA ya cultiva plantas para llevar durante el viaje a Marte.', '2012-10-21 10:51:00', 'Poner un hombre en el espacio no involucra sólo el medio de transporte. Otro de los factores esenciales es su alimentación. Con la mirada puesta en 2030 y la posibilidad de una expedición tripulada a Marte, la NASA comenzó a desarrollar el prototipo de un invernadero que permitirá cosechar vegetales en el espacio en forma automática.', 5, 5);

-- Data de Comentario

INSERT INTO `comentario` (`id`, `texto`, `fecha_hora`, `nota_id`, `usuario_id`, `comentador`) VALUES(1, 'Otra vez tenemos que cambiar de sistema operativo? Mejor me quedo con mi DOS...', '2012-10-20 00:07:00', 2, 2,'Carlos Fernandez' );
INSERT INTO `comentario` (`id`, `texto`, `fecha_hora`, `nota_id`, `usuario_id`, `comentador`) VALUES(2, 'Lo voy a probar... y posteriormente conseguir el crack de activación of course...', '2012-10-20 00:07:01', 2, NULL, 'Incognito' );
INSERT INTO `comentario` (`id`, `texto`, `fecha_hora`, `nota_id`, `usuario_id`, `comentador`) VALUES(3, 'Lo quiero en bailando 2013!!!', '2012-10-21 10:49:00', 3, 4,'Anibal Pachano' );
INSERT INTO `comentario` (`id`, `texto`, `fecha_hora`, `nota_id`, `usuario_id`, `comentador`) VALUES(4, 'Jajajajaja, me hace reir pachano', '2012-10-21 10:49:01', 3, NULL,'Silvina E.' );
INSERT INTO `comentario` (`id`, `texto`, `fecha_hora`, `nota_id`, `usuario_id`, `comentador`) VALUES(5, 'Llevarán uvas para hacer vino?', '2012-10-21 11:07:12', 3, NULL,'Pedro de Caseros' );